
export const subjects = {
	"ACC": "Accounting",
	"ARO": "Aerospace Engineering",
	"AG": "Agriculture",
	"ABM": "Agribusiness and Food Industry Management",
	"AGS": "Agricultural Science",
	"AHS": "Animal Health Science",
	"AMM": "Apparel Merchandising and Management",
	"ANT": "Anthropology",
	"ARC": "Architecture",
	"AH": "Art History",
	"AST": "Animal and Veterinary Science",
	"AVS": "Astronomy",
	"BIO": "Biology",
	"BUS": "Business",
	"CPU": "Cal Poly University",
	"CE": "Civil Engineering",
	"CHM": "Chemistry",
	"CHE": "Chemical Engineering",
	"CHN": "Chinese",
	"CIS": "Computer Information Systems",
	"CS": "Computer Science",
	"COM": "Communication",
	"CRM": "Criminology",
	"DAN": "Dance",
	"ECS": "Early Childhood Studies",
	"EBZ": "E-Business",
	"EC": "Economics",
	"EDU": "Education",
	"ECI": "Education Curriculum and Instruction",
	"EDL": "Educational Leadership",
	"EDD": "Educational Leadership Doctorate",
	"EMM": "Educational Multimedia",
	"ERA": "Educational Research and Assessment",
	"ECE": "Electrical and Computer Engineering",
	"ETE": "Electronic Systems Engineering Technology",
	"EGR": "Engineering",
	"EMT": "Engineering Management",
	"ETM": "Electromechanical Systems Engineering Technology",
	"ENG": "English",
	"EVN": "Environmental Design",
	"EWS": "Ethnic and Women's Studies",
	"FRL": "Finance, Real Estate, and Law",
	"FST": "Food Science and Technology",
	"FRE": "French",
	"GER": "German",
	"GBA": "Graduate Business Administration",
	"GEO": "Geography",
	"GSC": "Geological Sciences",
	"HST": "History",
	"HRT": "Hospitality Management",
	"IME": "Industrial and Manufacturing Engineering",
	"IE": "Industrial Engineering",
	"IGE": "Interdisciplinary General Education",
	"INA": "Interior Architecture",
	"IAM": "International Apparel Management",
	"IBM": "International Business and Marketing",
	"KIN": "Kinesiology and Health Promotion",
	"LA": "Landscape Architecture",
	"CLS": "Letters, Arts, and Social Sciences",
	"LS": "Liberal Studies",
	"LIB": "Library",
	"LRC": "Learning Resource Center",
	"MHR": "Management and Human Resources",
	"MFE": "Manufacturing Engineering",
	"MTE": "Materials Engineering",
	"MAE": "Mathematic Education",
	"MAT": "Mathematics",
	"ME": "Mechanical Engineering",
	"MSL": "Military Science and Leadership",
	"MU": "Music",
	"NTR": "Nutrition",
	"MPA": "Master of Public Administration",
	"PLT": "Plant Science",
	"PHY": "Physics",
	"PHL": "Philosophy",
	"PLS": "Political Science",
	"PSY": "Psychology",
	"RS": "Regenerative Studies",
	"SCI": "Science",
	"STS": "Science, Technology, and Society",
	"SME": "Science and Mathematics Education Center",
	"SOC": "Sociology",
	"SW": "Social Work",
	"SPN": "Spanish",
	"STA": "Statistics",
	"SE": "Systems Engineering",
	"TOM": "Technology and Operations Management",
	"TH": "Theatre",
	"URP": "Urban and Regional Planning",
	"VCD": "Visual Communication Design",
}
