version: "3.8"
services:
  postgresql:
    image: kle97/postgres-enrollment-system:latest
#    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=adminpass
      - POSTGRES_DB=enrollment_system
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6-alpine
    ports:
      - 6379:6379
    command: redis-server --requirepass redispass
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data: