version: "3.8"
services:
  angular:
    build:
      dockerfile: Dockerfile
      context: .
      target: frontend
    image: angular-enrollment-system:latest
    ports:
      - "4200:4200"
    depends_on:
      - spring-boot
  spring-boot:
    build:
      dockerfile: Dockerfile
      context: .
      target: backend
    image: spring-boot-enrollment-system:latest
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgresql
    depends_on:
      - redis
      - postgresql
  postgresql:
    image: kle97/postgres-enrollment-system:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=adminpass
      - POSTGRES_DB=enrollment_system
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: kle97/redis-enrollment-system:6.2.6-alpine
    ports:
      - "6379:6379"
    command: redis-server --requirepass redispass
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data: