export interface AdminEnrollment {
	studentId: string,
	sectionId: string,
	enrollmentStatus: string,
	accessCode: string,
	sectionNumber: number,
	meetingDays: string,
	meetingTimeStart: string,
	meetingTimeEnd: string,
	classCapacity: number,
	waitlistCapacity: number,
	enrolledNumber: number,
	waitingNumber: number,
	dateStart: string,
	dateEnd: string,
	sectionStatus: string,
	buildingNumber: number,
	roomNumber: number,
	instructorLastName: string,
	instructorFirstName: string,
	termName: string,
	courseCode: string,
	courseName: string,
	studentFirstName: string,
	studentLastName: string,
	studentEmail: string,
}
